Update CHANGEME.md
ParanoidUser/yolo pull request #925
Opened 2023-06-16 13:10 UTC by Heidet

yolo

2023-06-16 13:46 UTC, ParanoidUser commented
Ahoy, @Heidet! To earn the YOLO badge, please follow [these steps](https://github.com/ParanoidUser/yolo/discussions/18). Let me know if you have any questions.

2023-06-16 13:52 UTC, ParanoidUser requested changes

2023-06-16 13:52 UTC, ParanoidUser commented on CHANGEME.md
> +You take one down, you pass it around, 127 bottles of rum on the wall.
There should be 126 bottles.

2023-06-16 14:45 UTC, Heidet reviewed
126

2023-06-16 14:45 UTC, Heidet commented on CHANGEME.md
>  126 bottles of rum on the wall, 126 bottles of rum!
okay

2023-06-16 14:45 UTC, Heidet commented on CHANGEME.md
>  You take one down, you pass it around, 125 bottles of rum on the wall.
+

2023-06-20 20:14 UTC, ParanoidUser commented
Seems to be a duplicate of #929.

2023-06-20 20:14 UTC, closed without merging